"""NHAMCS predictive companion. Does not reinterpret length of visit as service work."""
from functools import lru_cache
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / 'resultados_ml'
FEATURES = ['age', 'sex', 'triage', 'temperature_c', 'pulse', 'respiration',
            'systolic', 'diastolic', 'pain', 'ambulance', 'arrival_hour']
RANGES = {'age': (0, 94), 'sex': (1, 2), 'triage': (1, 5),
          'temperature_c': (15, 45), 'pulse': (0, 350), 'respiration': (0, 150),
          'systolic': (0, 350), 'diastolic': (0, 250), 'pain': (0, 10),
          'ambulance': (0, 1), 'arrival_hour': (0, 23.9999)}
DISCRETE = {'sex', 'triage', 'ambulance'}


def clean_features(raw):
    """Only arrival/triage information; negative survey codes and Doppler become missing."""
    import numpy as np
    import pandas as pd
    x = pd.DataFrame(index=raw.index)
    mapping = {'age':'AGE','sex':'SEX','triage':'IMMEDR','pulse':'PULSE',
               'respiration':'RESPR','systolic':'BPSYS','diastolic':'BPDIAS','pain':'PAINSCALE'}
    for name, column in mapping.items():
        x[name] = pd.to_numeric(raw[column], errors='coerce').astype(float)
    temp = pd.to_numeric(raw['TEMPF'], errors='coerce')
    x['temperature_c'] = (temp.where(temp >= 0) / 10 - 32) * 5 / 9
    x['ambulance'] = pd.to_numeric(raw['ARREMS'], errors='coerce').map({1:1.,2:0.})
    hhmm = pd.to_numeric(raw['ARRTIME'], errors='coerce')
    valid = (hhmm >= 0) & (hhmm < 2400) & (hhmm % 100 < 60)
    x['arrival_hour'] = (hhmm // 100 + hhmm % 100 / 60).where(valid)
    for name, (lo, hi) in RANGES.items():
        x[name] = x[name].where(x[name].between(lo, hi), np.nan)
    return x[FEATURES]


def validate_profile(profile):
    if not isinstance(profile, dict) or set(profile) - set(FEATURES):
        raise ValueError('Perfil inválido o variables no admitidas.')
    result = {}
    for key in FEATURES:
        value = profile.get(key)
        if value is None:
            result[key] = float('nan')
            continue
        lo, hi = RANGES[key]
        if (type(value) not in (int,float) or not math.isfinite(value) or
                not lo <= value <= hi or (key in DISCRETE and int(value) != value)):
            raise ValueError(f'{key}: se requiere un número entre {lo} y {hi}, o null.')
        result[key] = float(value)
    if all(math.isnan(v) for v in result.values()):
        raise ValueError('Introduce al menos una variable del perfil.')
    return result


def model_status():
    path = ARTIFACTS / 'informe.json'
    if not path.exists():
        return {'available': False, 'message': 'Ejecuta python -m motor.train_ml para entrenar.'}
    report = json.loads(path.read_text(encoding='utf-8'))
    return {'available': (ARTIFACTS / 'modelos.joblib').exists(), 'report': report}


@lru_cache(maxsize=2)
def _load_models(stamp, expected_hash):
    import joblib
    path = ARTIFACTS / 'modelos.joblib'
    if hashlib.sha256(path.read_bytes()).hexdigest() != expected_hash:
        raise ValueError('El modelo no coincide con su informe; vuelve a entrenarlo.')
    # Fixed local artifact generated by our training command, never an uploaded pickle.
    return joblib.load(path)


def predict_profile(profile):
    values = validate_profile(profile)
    status = model_status()
    if not status['available']:
        raise ValueError('Modelo no disponible. Ejecuta python -m motor.train_ml.')
    import pandas as pd
    from threadpoolctl import threadpool_limits
    report = status['report']
    bundle = _load_models((ARTIFACTS/'modelos.joblib').stat().st_mtime_ns, report['model_sha256'])
    frame = pd.DataFrame([values], columns=FEATURES)
    predictions = {}
    with threadpool_limits(limits=2):
        for key, entry in bundle.items():
            if entry['model'] is None:
                value = entry['constant']
            elif key == 'hospitalization':
                value = float(entry['model'].predict_proba(frame)[0,1])
            else:
                value = max(0.,float(entry['model'].predict(frame)[0]))
            predictions[key] = {'value': value, 'method': entry['name'],
                                'test_metrics': report['targets'][key]['test_selected']}
    return {'predictions': predictions, 'missing_features': [k for k,v in values.items() if math.isnan(v)],
            'source': report['source'], 'model_sha256': report['model_sha256'],
            'scope': 'Predicción experimental NHAMCS 2022, EE. UU.; no validada en Perú ni en víctimas masivas. '
                     'La estancia incluye espera y no sustituye el trabajo asistencial del simulador.'}
